In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("Preplacement.csv")

In [3]:
dataset

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,1.0,67.00,91.00,58.00,55.0,58.80,270000.000000,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,2.0,79.33,78.33,77.48,86.5,66.28,200000.000000,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,3.0,65.00,68.00,64.00,75.0,57.80,250000.000000,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,4.0,56.00,52.00,52.00,66.0,59.43,288655.405405,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,5.0,85.80,73.60,73.30,96.8,55.50,425000.000000,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,211.0,80.60,82.00,77.60,91.0,74.49,400000.000000,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,212.0,58.00,60.00,72.00,74.0,53.62,275000.000000,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,213.0,67.00,67.00,73.00,59.0,69.72,295000.000000,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,214.0,74.00,66.00,58.00,70.0,60.23,204000.000000,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,215.0,62.00,58.00,53.00,89.0,60.22,288655.405405,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [4]:
dataset.isna().sum()

sl_no             0
ssc_p             0
hsc_p             0
degree_p          0
etest_p           0
mba_p             0
salary            0
gender            0
ssc_b             0
hsc_b             0
hsc_s             0
degree_t          0
workex            0
specialisation    0
status            0
dtype: int64

In [5]:
dataset.drop('sl_no',inplace=True,axis=1)

In [6]:
dataset

,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,67.00,91.00,58.00,55.0,58.80,270000.000000,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,79.33,78.33,77.48,86.5,66.28,200000.000000,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,65.00,68.00,64.00,75.0,57.80,250000.000000,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,56.00,52.00,52.00,66.0,59.43,288655.405405,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,85.80,73.60,73.30,96.8,55.50,425000.000000,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,80.60,82.00,77.60,91.0,74.49,400000.000000,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,58.00,60.00,72.00,74.0,53.62,275000.000000,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,67.00,67.00,73.00,59.0,69.72,295000.000000,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,74.00,66.00,58.00,70.0,60.23,204000.000000,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,62.00,58.00,53.00,89.0,60.22,288655.405405,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [7]:
def QuanQual(dataset):
    Quan = []
    Qual = []
    for columnName in dataset.columns:
        if(dataset[columnName].dtype=='O'):
            Qual.append(columnName)
        else:
            Quan.append(columnName)
    return Quan,Qual

In [8]:
QuanQual(dataset)

(['ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary'],
 ['gender',
  'ssc_b',
  'hsc_b',
  'hsc_s',
  'degree_t',
  'workex',
  'specialisation',
  'status'])

In [9]:
quan,qual = QuanQual(dataset)

In [10]:
dataset[quan]

     ssc_p  hsc_p  degree_p  etest_p  mba_p         salary
0    67.00  91.00     58.00     55.0  58.80  270000.000000
1    79.33  78.33     77.48     86.5  66.28  200000.000000
2    65.00  68.00     64.00     75.0  57.80  250000.000000
3    56.00  52.00     52.00     66.0  59.43  288655.405405
4    85.80  73.60     73.30     96.8  55.50  425000.000000
..     ...    ...       ...      ...    ...            ...
210  80.60  82.00     77.60     91.0  74.49  400000.000000
211  58.00  60.00     72.00     74.0  53.62  275000.000000
212  67.00  67.00     73.00     59.0  69.72  295000.000000
213  74.00  66.00     58.00     70.0  60.23  204000.000000
214  62.00  58.00     53.00     89.0  60.22  288655.405405

[215 rows x 6 columns]

In [11]:
dataset[qual]

,gender,ssc_b,hsc_b,hsc_s,degree_t,workex,specialisation,status
0,M,Others,Others,Commerce,Sci&Tech,No,Mkt&HR,Placed
1,M,Central,Others,Science,Sci&Tech,Yes,Mkt&Fin,Placed
2,M,Central,Central,Arts,Comm&Mgmt,No,Mkt&Fin,Placed
3,M,Central,Central,Science,Sci&Tech,No,Mkt&HR,Not Placed
4,M,Central,Central,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
...,...,...,...,...,...,...,...,...
210,M,Others,Others,Commerce,Comm&Mgmt,No,Mkt&Fin,Placed
211,M,Others,Others,Science,Sci&Tech,No,Mkt&Fin,Placed
212,M,Others,Others,Commerce,Comm&Mgmt,Yes,Mkt&Fin,Placed
213,F,Others,Others,Commerce,Comm&Mgmt,No,Mkt&HR,Placed
214,M,Central,Others,Science,Comm&Mgmt,No,Mkt&HR,Not Placed

In [ ]:
# Independent sample - Unpaird T Test

In [ ]:
# diff group (Male,female) bt same condition (salary)

In [16]:
from scipy.stats import ttest_ind
male = dataset[dataset['gender']=='M']['salary']
female = dataset[dataset['gender']=='F']['salary']
ttest_ind(male, female)

TtestResult(statistic=1.9001627265152634, pvalue=0.05876239427122642, df=213.0)

In [17]:
# Dependant Sample - Paired T_Test

In [ ]:
# Same Group (Male) but Different Condition (ssc_p,hsc_p)

In [14]:
from scipy.stats import ttest_rel
male = dataset[dataset['gender']=='M']['ssc_p']
male1 = dataset[dataset['gender']=='M']['hsc_p']
ttest_rel(male, male1)

TtestResult(statistic=0.6852881050898076, pvalue=0.49431164600731514, df=138)

In [18]:
# Assignment

In [19]:
# 1. different group hsc_s='Commerce','Science' but same condition(mba_p)

In [23]:
from scipy.stats import ttest_ind
Commerce = dataset[dataset['hsc_s']=='Commerce']['mba_p']
Science = dataset[dataset['hsc_s']=='Science']['mba_p']
ttest_ind(Commerce, Science)

TtestResult(statistic=-0.7331285580404581, pvalue=0.46432995253854314, df=202.0)

In [24]:
# 2. same group hsc_s='Commerce' but Different Condition(etest_p,mba_p)

In [25]:
from scipy.stats import ttest_rel
Commerce1 = dataset[dataset['hsc_s']=='Commerce']['etest_p']
Commerce2 = dataset[dataset['hsc_s']=='Commerce']['mba_p']
ttest_rel(Commerce1, Commerce2)

TtestResult(statistic=7.868552092606871, pvalue=2.462926468454984e-12, df=112)